# Generated by Django 4.1.1 on 2022-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('plot', models.CharField(max_length=5)),
                ('startTime', models.CharField(max_length=15)),
                ('endTime', models.CharField(max_length=15)),
                ('Runby', models.CharField(max_length=10)),
            ],
        ),
    ]
